### Publish Article
POST http://localhost:4000/author-api/article
Content-Type: application/json

{
  "author": "PUT_AUTHOR_ID_HERE",
  "title": "Future of AI",
  "category": "Technology",
  "content": "Artificial Intelligence is rapidly changing the world."
}

###

### View Own Articles
GET http://localhost:4000/author-api/articles

###

### Deactivate Article
PATCH http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "articleId": "PUT_ARTICLE_ID_HERE",
  "isArticleActive": false
}

###

### Activate Article
PATCH http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "articleId": "PUT_ARTICLE_ID_HERE",
  "isArticleActive": true
}